name: flutter_tdd_clean_architecture_code_alberto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Service locator
  get_it: ^6.0.0
  
  # Bloc for state management
  flutter_bloc: ^6.1.3
  
  # Value equality
  equatable: ^2.0.0
  
  # Functional programming thingies
  dartz: ^0.9.2
  
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.0

  # Local cache
  shared_preferences: ^2.0.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
  bloc_test: ^7.1.0


flutter:
  uses-material-design: true
